version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: reader_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_USER: user
      MONGO_PASS: pass
      MONGO_DB: Reader
      MONGO_HOST: mongodb
    depends_on:
      - mongodb
    volumes:
      - .:/app

volumes:
  mongo-data:
